col file_name form a55;
col file_id form a8;
SELECT A.FILE_ID, A.TABLESPACE_NAME, A.FILE_NAME, B.CREATION_TIME, (A.BYTES)/1024/1024 SIZEMB
FROM DBA_DATA_FILES A, V$DATAFILE_HEADER B
WHERE A.TABLESPACE_NAME='&TBS'
AND A.FILE_ID=B.FILE#
ORDER BY B.CREATION_TIME;  